name: Notion2Github
on:
  push:
    branches:
      - main
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notion2Github
        uses: younho9/notion2github@v1.1.0
        with:
          database-url: 'https://www.notion.so/1c29f6b165cc47579b243e7dab74f83d'
          docs-directory: ./
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}


